-- hosp_kpis installer placeholder
-- The production installer falls back to db/hospital_kpi.sql when this file has no executable SQL.
-- Replace this file with a schema-only export if you want a dedicated schema artifact.
